Turtle anim
aleksandralis/turtle_game pull request #6
Opened 2018-10-01 20:17 UTC by aleksandralis

2018-10-01 20:43 UTC, kpiaskowski requested changes

2018-10-01 20:43 UTC, kpiaskowski commented on source/turtles/turtle_hero.py
> +        self.image_sheet = pygame.image.load('D:\\Users\\Ola\\PycharmProjects\\turtle_game\\source\\turtles\\sv_turtle_sheet.png').convert_alpha()
It won't work on any machine but yours. Use relative paths.

2018-10-01 20:43 UTC, kpiaskowski commented on source/turtles/turtle_hero.py
> +        self.is_jumping = JumpStates.IDLE# jumping state machine: 0 - no jumping, 1 - jump up, 2 - jump down
Hmm, that comment is a bit confusing, since the *jump_states* are now being treated as enums. Delete it.

2018-10-01 20:43 UTC, kpiaskowski commented on source/turtles/turtle_hero.py
> +        self.image = self.get_image(self.walk_r[1][0] * self.WIDTH, self.walk_r[1][1] * self.HEIGHT, self.WIDTH, self.HEIGHT)
`self.image = self.get_image(self.walk_r[1][0] * self.WIDTH, self.walk_r[1][1] * self.HEIGHT, self.WIDTH, self.HEIGHT)`
In the update_anim_[..] functions, the only things that seem to change are the indices used to access `self.walk_r`. Would't it be much cleaner to make a separate function wrapping around `self.image = self.get_image(self.walk_r[1][0] * self.WIDTH, self.walk_r[1][1] * self.HEIGHT, self.WIDTH, self.HEIGHT)` and taking indices as arguments?

2018-10-01 20:43 UTC, kpiaskowski commented on source/turtles/turtle_hero.py
> +    def update_anim_stop_rigth(self):
typo in 'right'

2018-10-02 20:25 UTC, aleksandralis commented on source/turtles/turtle_hero.py
> +        self.image_sheet = pygame.image.load('D:\\Users\\Ola\\PycharmProjects\\turtle_game\\source\\turtles\\sv_turtle_sheet.png').convert_alpha()
No, I think everyone should have disk D (if you have only C disk then you should go to the shop and ask for the D one), moreover folder Ola is necessary.

2018-10-03 20:10 UTC, kpiaskowski approved these changes

2018-10-03 20:10 UTC, kpiaskowski commented on source/turtles/turtle_hero.py
> +        print(__file__)
I would prefer to not have such unnecessary lines in project
.
.
.
.
.
.
HUE HUE xd

2018-10-08 19:46 UTC, merged